### ISSUE TITLE
[FEATURE] 공유일기 초기 페이지

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#1]
### 🤸 Describe the required feature
공유일기 초기 페이지 구현

###  🏊 Todo
- [x] tailwind-styled-components 설정, recoil 설정
- [x] 페이지 라우팅 기능 추가
- [x] 페이지 배경화면, 비율 설정
- [x] nav bar 구현
- [x] 일기장 생성 페이지 라우팅
- [x] 컴포넌트 추가, 배치
- [x] animation 등 css 작업 

### 💬 Additional information
<img width="382" alt="image" src="https://user-images.githubusercontent.com/111125577/212738238-3098bc03-cf86-45df-9d9e-538c8377a48a.png">
