### ISSUE TITLE
[FEATURE] 게시글 상세 페이지 - 게시글/댓글 삭제 경고 모달창

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#122]
### 🤸 Describe the required feature
- 게시글/댓글 삭제 시 리워드로 주어졌던 포도알이 반납되기 때문에 삭제 전 해당 사항을 알려주는 경고 모달창이 필요함.

###  🏊 Todo
- [x] 모달창 배치 및 디자인, 반응형 작업
- [x] 게시글/댓글 삭제 버튼 클릭 시 삭제 경고 모달창 띄우기
- [x] X 버튼이나 모달창 바깥 눌렀을 때 모달창 닫기

### 💬 Additional information
**figma 캡쳐**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/217782263-84de7588-f97c-4c9a-bfce-40ea69246e9b.png">
