### ISSUE TITLE
[FEATURE] 게시글 상세 페이지 - 일기 작성자 게시글 내용 및 사진 수정, 삭제

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#125]
### 🤸 Describe the required feature
일기 작성자에 한해 드롭박스 버튼 -> 게시글 수정, 삭제 기능

###  🏊 Todo
- [x] 일기 작성자  === userId에 한해 드롭박스 버튼 주기
- [x] 수정 버튼 클릭 -> 일기 수정페이지로 이동
- [x] 일기 제목, 내용 patch 요청
- [x] #132
- [x] 삭제 버튼 클릭 -> 모달창 -> 삭제 
- [x] 디자인, 반응형 작업

### 💬 Additional information
**figma 캡쳐**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/218024959-d490af65-9cc8-4b7c-a372-7338d6ec5f6d.png">
