### ISSUE TITLE
[FEATURE] 게시글 상세 페이지 - 스티커 붙이기/떼기/움직이기, 저장

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#137]
### 🤸 Describe the required feature
스티커 버튼 클릭 후 스티커 편집 기능 구현 필요

###  🏊 Todo
- [x] 내 스티커팩 불러오기
- [x] 스티커 버튼 -> 클릭 시 스티커 편집모드로 전환(스티커 박스+아래 추가 공간+저장 버튼 보여주기), 버튼 재 클릭하거나 x 버튼 누르면 편집모드 해제
- [x] 스티커팩 선택 -> 스티커팩 이름 밑줄, 스티커 미리보기와 유효기간 바꿔서 띄워주기
- [x] 스티커 박스에서 스티커 선택 -> 선택한 스티커 + 스티커 옆 x 버튼 화면 중간에 띄우기
- [x] 스티커 동시에 여러개 편집, post 가능하도록 구현
  - [x] #143
  - [x] #154
- [x] 띄운 스티커 drag 기능
- [x] 스티커 옆 x 버튼 누르면 일기 위 스티커 없애주기
- [x] 스티커 위치 산출 및 저장, 반응형 대응해 상대 위치 계산 및 변환 로직 포함
- [x] 저장 버튼 클릭 시 스티커 위치 post

### 💬 Additional information
**figma 캡쳐**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/219610424-1b7d1cb0-b47b-46a6-aca8-b16a3af331e5.png">
