### ISSUE TITLE
[FEATURE] 일기장 생성 페이지

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#14]
### 🤸 Describe the required feature
일기장 생성 페이지 기능 구현, 디자인 작업

###  🏊 Todo
- [x] 뒤로 가기 기능
- [x] 표지 색상 선택, 선택된 색상만 dashed border로 보여주기
- [x] 선택 색상에 따라 다이어리 이미지 변경
- [x] 일기장 제목 입력, 제목 길이 제한, 현재 글자 수 보여주기
- [x] 생성하기 버튼 클릭 시 제목 글자수 검사 후 {일기장 색상 + 제목} post 요청
- [x] 디자인 작업, 반응형으로 만들기

### 💬 Additional information
**figma 캡쳐**
<img width="513" alt="image" src="https://user-images.githubusercontent.com/111125577/213979467-74e05bca-5c85-42be-b383-17e413a26d70.png">
