### ISSUE TITLE
[FEATURE] 포도알 페이지 - 내 포도

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#158]
### 🤸 Describe the required feature
포도알 페이지 기능 구현 및 디자인 
###  🏊 Todo
- [x] 내 포도송이, 포도알 개수 받아와서 표시
- [x] 포도알 개수에 맞는 이미지 보여주기
- [x] 스티커샵 이동 버튼 클릭 시 스티커샵 컴포넌트 있는 부분으로 스크롤 이동
- [x] 스크롤 내려도 nav bar 고정되도록 수정
- [x] 디자인, 반응형 작업

### 💬 Additional information
**figma 캡쳐**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/219975051-876dc1fe-86b8-4cb0-b937-490e7c796bbf.png">
