### ISSUE TITLE
[FEATURE] 게시글 상세 페이지 - 붙은 스티커 보여주기, drag and drop 기능

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#159]
### 🤸 Describe the required feature
일기에 붙여진 스티커들 보여주기, 그 스티커들 움직일 수 있게 하기

###  🏊 Todo
- [x] 일기에 붙여진 스티커들 불러와서 맞는 위치에 보여주기 
- [x] 스티커들 치우고 볼 수 있게 drag and drop 기능 추가
- [x] 원래 붙어있었던 스티커는 moveable box 기본 테두리 안보이게 해서 위치 편집중인 스티커와 구분되게 하기 
- [x] 스티커 저장 후 방금 붙인 스티커 화면에 바로 보여주기
- [x] 일기 배경, 일기 작성자 정보 & 일기 내용 공통 컴포넌트로 분리 
- [x] z-index, align 등 css 수정

### 💬 Additional information
**figma 캡쳐**
<img width="557" alt="image" src="https://user-images.githubusercontent.com/111125577/219864524-647acc2e-dbb4-4d96-8383-4701a04fa8ce.png">

+ repo 다시 받고 git hooks 설정 늦게 해서 일부 커밋들 tracking이 누락됨 😱
