### ISSUE TITLE
[FEATURE] 글 리스트 페이지 - 붙은 스티커 보여주기, drag and drop 기능

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#165]
### 🤸 Describe the required feature
글 리스트 페이지에서도 붙은 스티커들을 보여주기로 결정함에 따라 댓글 내용을 제외한 부분까지 스티커 보여주기
###  🏊 Todo
- [x] 일기에 붙여진 스티커들 불러와서 맞는 위치에 보여주기 
- [x] 일기 상세 페이지와 같은 위치에 스티커 붙도록 일기 컴포넌트 재활용
- [x] 스티커들 치우고 볼 수 있게 drag and drop 기능 추가
- [x] moveable box 기본 테두리 안보이게 처리

### 💬 Additional information
**figma 캡쳐**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/219865139-08be9645-fc49-4b22-b600-5df906c99d3c.png">
