### ISSUE TITLE
[FEATURE] Navigation Bar 기능 완성, css 보완

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#172]
### 🤸 Describe the required feature
Navigation Bar 기능 완성, css 보완

###  🏊 Todo
- [x] nav bar의 아이콘 색상 현재 페이지에 맞게 highlight
- [x] 수직 위치 고정, nav bar shadow 추가
- [x] nav bar 내 아이콘 shadow, hover효과 추가

### 💬 Additional information
**before**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/219960663-7973fed7-a0a2-4ec5-918b-59d330c82b52.png">
