### ISSUE TITLE
[FEATURE] 포도알 페이지 - 스티커 샵

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#175]
### 🤸 Describe the required feature
스티커샵 페이지 기능 구현, 디자인 작업
###  🏊 Todo
- [x] 내 포도알 버튼 클릭 시 포도 정보 부분으로 스크롤 이동
- [x] 포도송이 개수 보여주기
- [x] 소유중이지 않은 패키지 받아와서 보여주기
- [x] 패키지 리스트에서 패키지 선택 시 패키지 상세 창 띄우기, x 버튼 클릭 시 패키지 리스트 띄우기
- [x] 패키지 구매 버튼 클릭 시 구매 post, 포도 차감 처리 후 리스트 화면으로 돌아가기
- [x] 가진 포도송이 개수보다 패키지 가격이 비쌀 때 구매 버튼 비활성화 하기
- [x] 디자인, 반응형 작업

### 💬 Additional information
<img width="960" alt="image" src="https://user-images.githubusercontent.com/111125577/220204359-5808096a-7fd6-4247-a5a0-c9d47d952fc0.png">
