### ISSUE TITLE
[FEATURE] 마이페이지 - 마이페이지 메인

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#182]
### 🤸 Describe the required feature
마이페이지 메인 기능 구현 및 디자인 작업

###  🏊 Todo
- [x] 유저 정보 받아와서 뿌리기
- [x] 정보 수정 페이지 이동
- [x] 초대 코드 입력 후 일기장 들어가기 요청
- [x] 로그아웃
- [x] 탈퇴하기
- [x] 디자인 및 반응형 작업

### 💬 Additional information
**figma 캡쳐**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/220316497-a58767c0-4533-4cd8-af09-b81616fef3e0.png">
