### ISSUE TITLE
[STYLE] 디자인 보완, 반응형 크기 수정

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#189]
### 🤸 Describe the required feature
디자인 보완, 모바일에서 너무 크거나 작게 보이는 부분 수정

###  🏊 Todo
- [x] 폰트 noto sans -> sans로 변경
- [x] 패키지 리스트 길이 늘리기
- [x] 패키지 상세창 x 버튼 hover 투명도 주기
- [x] sns 계정으로 로그인하기 글자, 아이콘 조금 큼 
- [x] 댓글 아이콘 너무 큼
- [x] 초대코드 새로고침 버튼 넓이 조절
- [x] 일기장 공유멤버 프사 큼
- [x] 일기장 만들기, 수정페이지 내 섹션 제목 큼
- [x] 수정/삭제 드롭다운 작음  
- [x] 삭제 모달창 크기 작음
- [x] 일기장 안내문구, 새 일기장 만들기 문구 큼
- [x] 뒤로가기 아이콘, 설정 아이콘 조금 큼
- [x] input창 padding , 보라 버튼 작음
