### ISSUE TITLE
[FEATURE] UI 개선 - 스크롤바 추가 및 숨기기, 스티커팩 박스 길이 조절

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#214]
### 🤸 Describe the required feature
UI 개선

###  🏊 Todo
- [x] 스크롤 바 필요한 부분 추가
- [x] 스크롤 바 스타일 숨기기
- [x] 스티커샵 패키지 박스 길이 조절

### 💬 Additional information
**before**
<div>
  <img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/225827837-600ce3e6-c338-4ef6-a9ce-8cf7253d8c5b.png">
  <img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/225827873-9748c5b5-6b58-48f4-b7be-232721209e89.png">
</div>
