### ISSUE TITLE
[REFACTOR] 웹 성능 최적화 - javascript bundle 경량화

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#224]
### 🤸 Describe the required feature
javascript bundle 사이즈가 매우 커 초기 페이지 로딩 성능을 저하시키는 것으로 보임. 번들 분석 후 경량화 작업이 필요함.

###  🏊 Todo
- [x] webpack bundle analyzer로 번들 구성 분석
- [x] 라이브러리 크기 줄이기
- [x] lazy loading(dynamic import)
- [x] 필요없는 코드 없애기
- [x] 이미지 파일 번들에서 제외
- [x] code-splitting

### 💬 Additional information
**개선 전 번들 크기**
stat size 3.9mb
gzipped size 642.14kb
![image](https://user-images.githubusercontent.com/111125577/232480916-c80a8e3f-f418-4fa5-a6c9-9db95b668a70.png)
