### ISSUE TITLE
[REFACTOR] 웹 성능 최적화 - 이미지 최적화

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#226]
### 🤸 Describe the required feature
- 아이콘 이미지 로드에 생기는 병목 개선
- 일기 첨부 이미지 로드 전 자리 차지하지 않다가 로드 후 서서히 나타나는 문제 개선 (CLS 지표에 악영향 끼치는 것으로 보임)

###  🏊 Todo
- [x] width, height 명시되어있지 않아 비효율 발생하는 부분 수정
- [x] 필요한 해상도에 비해 지나치게 큰 아이콘들 해상도 조절
- [x] 아이콘 이미지 webp 사용, picture tag로 호환성 고려
- [x] 일기 첨부 이미지 로드 중 skeleton UI 띄우기

### 💬 Additional information
**일기 첨부 이미지 로드 전 자리 차지하지 않다가 로드 후 서서히 나타나는 이슈** 
<div>
  <img width="350" alt="image" src="https://user-images.githubusercontent.com/111125577/233581698-841a4c53-3b46-419f-8616-236814036a23.png">
  <img width="350" alt="image" src="https://user-images.githubusercontent.com/111125577/233581441-36ba0d2c-0b0d-4e35-9ae2-a7d5e1c9c85d.png">
</div>

**개선 전 성능 (홈화면/일기 화면)**
<div>
  <img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/233602286-d4631d73-afa6-499e-867d-74cb5b76be6a.png">
  <img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/233580257-476fa9eb-e355-45dd-ab78-e58997762dc5.png">
</div>
