### ISSUE TITLE
[FEATURE] 댓글 로딩 상태 Skeleton UI 적용

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#228]
### 🤸 Describe the required feature
댓글 로딩 중 skeleton UI 보여주기

###  🏊 Todo
- [x] 댓글 skeleton 컴포넌트 추가
- [x] 댓글 개수만큼 skeleton 보여주기
  - [x] location state로 받은 댓글 개수를 초기 댓글 개수 state로 설정
  - [x] 이후 댓글 업데이트 될 때 댓글 개수 state 업데이트
