### ISSUE TITLE
[FEATURE] 홈화면 페이지

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#23]
### 🤸 Describe the required feature
홈화면 페이지 기능 구현, 디자인 작업

###  🏊 Todo
- [x] animated gradient background
- [x] Fade in 효과
- [x] 소셜로그인(네이버, 카카오) 버튼 디자인
- [x] api, cookie 관련 함수들 추가
- [x] 로그인 입력값 검사, react-hook-form 사용
- [x] 이메일 로그인 api 요청, 로그인 처리 (cookie)
- [x] 회원가입 버튼 -> 회원가입 페이지로 이동
- [x] 로그인 상태면 회원가입/로그인 버튼 숨기기 & 일정시간 후 일기장 리스트 페이지로 보내기
- [x] 디자인 작업, 반응형으로 만들기

### 💬 Additional information
**figma 캡쳐**
<img width="893" alt="image" src="https://user-images.githubusercontent.com/111125577/214921243-dc187a00-c57f-4bf7-b451-fcf6af8562b9.png">
