### ISSUE TITLE
[REFACTOR] types, styles 파일 분리 및 export-import 개선

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#230]
### 🤸 Describe the required feature
- type과 css 코드들이 각 컴포넌트들에 분산되어있어 파악하기 힘들고 불필요하게 반복되는 부분이 있음. 분산되어 있는 코드를 모으고 반복되는 코드를 없애기
- 페이지 별 컴포넌트들을 index.ts에서 모아서 export해 불필요한 import문 반복을 피하기
 
###  🏊 Todo
- [x] component 파일에서 props type 코드를 제외한 다른 type은 `@types` 디렉토리 아래로 분리
- [x] 유틸리티 타입을 활용해 반복되는 타입 처리, 안정성 향상시키기
- [x] css 코드는 page 별로 `styles` 디렉토리 아래에 분리
- [x] styled-components는 S.컴포넌트로 사용해 일반 컴포넌트와 구분
- [x] page 별 컴포넌트들 index.ts에서 모아서 export해 page 컴포넌트에서 한번에 불러올 수 있도록 관리

### 💬 Additional information
book이라는 페이지 네이밍이 일기 리스트가 보이는 일기장 페이지라는 것을 잘 드러내지 못하는 것으로 판단됨. book -> diary-list로 이름을 변경하기
