### ISSUE TITLE
[FEATURE] headers authorization token 주기, api 변경에 따른 코드 수정

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#70]
### 🤸 Describe the required feature
토큰 저장방식 수정에 따른 auth 권한 필요 api 요청 수정, api 변경에 따른 코드 수정

###  🏊 Todo
- [x] access token 저장 위치 변경에 따라 auth 권한 필요한 api 요청시 token 넣어주기
- [x] api response 객체 변경에 따른 코드 수정
- [x] api 완성에 따라 mock data를 api get요청해서 받아온 데이터로 수정
- [x] 프로필 사진, 게시물 사진, 댓글 개수 추가
