### ISSUE TITLE
[FEATURE] 유저 기능 개발

### ISSUE THREAD

**Issue by ahosang** [sojinjang/podo-log#8]
### 🤸 Describe the required feature
유저 CRUD 및 약한 탈퇴

###  🏊 Todo
- [x] 로컬 회원 가입
- [x] 유저 정보 조회
- [x] 유저 정보 수정
- [x] 약한 탈퇴
- [x] 유저 정보 탈퇴
