### ISSUE TITLE
[FEATURE] 일기장 생성 페이지 api 연결, 디자인 수정 및 리팩토링

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#80]
### 🤸 Describe the required feature
일기장 생성 페이지 api 연결, 디자인 수정 및 리팩토링

###  🏊 Todo
- [x] recoil title atom, 버튼에 submit callback 함수 전달 방식에서 react-hooks-form 이용하도록 구현방법 변경
- [x] 일기장 생성 post api 연결
- [x] 일기장 색상 cleanup 기능
- [x] 배경화면 변경, animation
