### ISSUE TITLE
[FEATURE] 게시글 상세 페이지 - 댓글 가져오기, 댓글 달기

### ISSUE THREAD

**Issue by sojinjang** [sojinjang/podo-log#99]
### 🤸 Describe the required feature
상세페이지 댓글 달기 창 디자인, 댓글 달기 기능 구현

###  🏊 Todo
- [x] 상세페이지 전체적인 마크업
- [x] 댓글 데이터 뿌리기
- [x] 댓글 달기
- [x] 디자인, 반응형 작업

### 💬 Additional information
**figma 캡쳐**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111125577/217261917-ee5c2382-55fb-4f16-aa56-b078a076c918.png">
